### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by kbshal** [Snawoot/hisilicon-dvr-telnet#4]
I tried but it didn't open the port instead it says can i know what's the reason for this error?

root@localhost:~/hisilicon-dvr-telnet# ./hs-dvr-telnet 192.168.10.11 2wj9fsa2

Sent OpenTelnet:OpenOnce command.
randNum:97615224
challenge=976152242wj9fsa2
verify:OK
Retry:Internet
Open failed.

**Comment by Snawoot** [comment]
Duplicates #1

**Comment by kbshal** [comment]
Okay....what's the solution for this issue??
